#prometheus.yml - file
#this must be in the same directory as of docker-compose.yml file
global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
- job_name: cadvisor
  static_configs:
  - targets:
    - cadvisor:8080
- job_name: redis
  static_configs:
  - targets:
    - redis:9121
